/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "Serialization/Hash/CrcHardware.h"
#include "Serialization/Hash/CrcSoftware.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ordinary_CrcHardware();
extern void test_ordinary_CrcSoftware();
extern void test_first_CrcHardware();
extern void test_first_CrcSoftware();
extern void test_lucky_CrcHardware();
extern void test_lucky_CrcSoftware();
extern void test_forced_crc8_collision();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/logic/test_Hashing/test.cpp");
  run_test(test_ordinary_CrcHardware, "test_ordinary_CrcHardware", 19);
  run_test(test_ordinary_CrcSoftware, "test_ordinary_CrcSoftware", 23);
  run_test(test_first_CrcHardware, "test_first_CrcHardware", 42);
  run_test(test_first_CrcSoftware, "test_first_CrcSoftware", 46);
  run_test(test_lucky_CrcHardware, "test_lucky_CrcHardware", 67);
  run_test(test_lucky_CrcSoftware, "test_lucky_CrcSoftware", 71);
  run_test(test_forced_crc8_collision, "test_forced_crc8_collision", 75);

  return UnityEnd();
}
